tests = [
    {"initial": {"shownColumns": "id,lastName", "hiddenColumns": ""},
     "expected": ["id", "lastName"]},
    {"initial": {"shownColumns": "", "hiddenColumns": "age"},
     "expected": ["id", "firstName", "lastName"]},
    {"initial": {"shownColumns": "id,firstName", "hiddenColumns": "age"},
     "expected": ["id", "firstName", "lastName"]},
    {"initial": {"shownColumns": "id,lastName", "hiddenColumns": ""},
     "updateWith": {"shownColumns": "id,firstName,lastName", "hiddenColumns": ""},
     "expected": ["id", "firstName", "lastName"]},
    {"initial": {"shownColumns": "id,lastName", "hiddenColumns": ""},
     "updateWith": {"shownColumns": "id,lastName", "hiddenColumns": "age"},
     "expected": ["id", "firstName", "lastName"]},
    {"initial": {"shownColumns": "", "hiddenColumns": "age"},
     "updateWith": {"shownColumns": "", "hiddenColumns": "id,age"},
     "expected": ["firstName", "lastName"]},
    {"initial": {"shownColumns": "", "hiddenColumns": "age"},
     "updateWith": {"shownColumns": "firstName", "hiddenColumns": "id,age"},
     "expected": ["firstName", "lastName"]},
    {"initial": {"shownColumns": "id,lastName", "hiddenColumns": "age"},
     "updateWith": {"shownColumns": "firstName,lastName", "hiddenColumns": "id,age"},
     "expected": ["firstName", "lastName"]},
    {"initial": {"shownColumns": "id,firstName", "hiddenColumns": ""},
     "updateWith": {"shownColumns": "id,lastName", "hiddenColumns": ""},
     "expected": ["id", "lastName"]}
]
