AWSTemplateFormatVersion: 2010-09-09
Description: IAM user for test case
Parameters:
  userName:
    Type: String
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref userName
      Policies:
        - PolicyName: dataaccess-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lakeformation:GetDataAccess
                  - athena:*
                  - glue:GetTable
                  - glue:GetTables
                  - glue:SearchTables
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetPartitions
                Resource: '*'
              - Sid: VisualEditor1
                Effect: Allow
                Action:
                  - s3:GetLifecycleConfiguration
                  - s3:GetBucketTagging
                  - s3:GetInventoryConfiguration
                  - s3:DeleteObjectVersion
                  - s3:GetObjectVersionTagging
                  - s3:ListBucketVersions
                  - s3:GetBucketLogging
                  - s3:ListBucket
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketPolicy
                  - s3:GetStorageLensConfigurationTagging
                  - s3:GetObjectVersionTorrent
                  - s3:GetObjectAcl
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetBucketRequestPayment
                  - s3:GetAccessPointPolicyStatus
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectTagging
                  - s3:GetMetricsConfiguration
                  - s3:GetBucketOwnershipControls
                  - s3:DeleteObject
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketPolicyStatus
                  - s3:ListBucketMultipartUploads
                  - s3:GetObjectRetention
                  - s3:GetBucketWebsite
                  - s3:GetJobTagging
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetObjectLegalHold
                  - s3:GetBucketNotification
                  - s3:GetReplicationConfiguration
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetStorageLensConfiguration
                  - s3:GetObjectTorrent
                  - s3:DescribeJob
                  - s3:GetBucketCORS
                  - s3:GetAnalyticsConfiguration
                  - s3:GetObjectVersionForReplication
                  - s3:GetBucketLocation
                  - s3:GetAccessPointPolicy
                  - s3:GetObjectVersion
                  - s3:GetStorageLensDashboard
                Resource:
                  - !Sub 'arn:aws:s3:::athena-output-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::athena-output-${AWS::AccountId}/*'
