AWSTemplateFormatVersion: 2010-09-09
Description: IAM user for test case
Parameters:
  userName:
    Type: String
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref userName
      Policies:
        - PolicyName: dataaccess-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lakeformation:GetDataAccess
                  - athena:*
                  - glue:GetTable
                  - glue:GetTables
                  - glue:SearchTables
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetPartitions
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::athena-output-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::athena-output-${AWS::AccountId}/*'
